### ISSUE TITLE
Finalize site copy

### ISSUE THREAD

**Issue by sschafft** [biveeco/bivee-site#17]
**Approval HC:**
- [x] 1. Home page copy
- [x] 2. Design thinking page

**Approval NF:**
- [x] 1. Home page copy
- [x] 2. Design thinking page

**Approval TSO:**
- [x] 1. Home page copy
- [x] 2. Design thinking page

**Approval JP:**
- [x] 1. Home page copy
- [x] 2. Design thinking page

**Comment by hcline** [comment]
@jayperryworks @NestorFuentes @sschafft please review for **1. Tag line** and **2. Intro blurbs** https://docs.google.com/document/d/1kL5CoVp0NMzAKRN5Z0C-xeUfeiEUnNbmgbyVvQA16oQ/edit#

**Comment by hcline** [comment]
@jayperryworks @NestorFuentes i've integrated all comments/suggestions from everyone's review, i would like to close and finalize the home page copy: https://docs.google.com/document/d/1SlknatYc3i8U-fk13Gf-MWbwAZcfdttt4NxgyHXBOCk/edit# please give it a final read and request any changes/mark progress here. thanks!

**Comment by hcline** [comment]
Removing staff bios and making them their own issue

**Comment by hcline** [comment]
Updated tasks to reflect reviews that have been conducted. Removed About page as they are their own issue.
