### ISSUE TITLE
As a user, I should see photos of work that has been done.

### ISSUE THREAD

**Issue by hcline** [biveeco/bivee-site#5]
- [ ] choose images for case studies

**Comment by hcline** [comment]
@jayperryworks would you like me to be working on this, or can it be iceboxed for this sprint?

**Comment by jayperryworks** [comment]
@hcline hmm, I'm not sure, actually, what the scope of this issue is -- it seems like this might already be done? I mean we've got imagery for case studies more or less covered. We might want to add more later, but it might make more sense to address that in a new issue...

**Comment by jayperryworks** [comment]
ah yeah, looking at the history it looks like this was completed in the last sprint, but then got pulled into this sprint for some reason. I might have mistakenly added it before the kickoff last week.

**Comment by hcline** [comment]
got it, should i close it?

**Comment by jayperryworks** [comment]
yeah, sounds good. yay doneness!
