### ISSUE TITLE
As a user I can see a product / project page

### ISSUE THREAD

**Issue by sschafft** [biveeco/bivee-site#88]
- [x] Add link to the product and project page to home page
- [x] Add page with products / consulting projects

**Comment by jayperryworks** [comment]
![core content](https://user-images.githubusercontent.com/1044536/51640886-bf4f9380-1f32-11e9-9a03-f9feaffcfa6b.jpeg)

**Comment by jayperryworks** [comment]
![core content](https://user-images.githubusercontent.com/1044536/51640915-d1c9cd00-1f32-11e9-82ea-78d20fd5537d.jpeg)
